services:
  - type: web
    name: social-media-research-api
    env: node
    plan: free
    region: oregon
    buildCommand: "npm install --no-audit --no-fund"
    startCommand: "node server/yt.js"
    autoDeploy: true
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PORT
        value: 8820
      - key: DATA_DIR
        value: /opt/render/project/src/data
      # 아래 키들은 Render 대시보드에서 안전하게 설정하세요
      # - key: YT_API_KEY
      #   sync: false
      # - key: OPENAI_API_KEY
      #   sync: false
      # - key: GEMINI_API_KEY
      #   sync: false
      # - key: LLM_PROVIDER
      #   value: openai
      # - key: CORS_ORIGIN
      #   value: https://your-app.vercel.app
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
